name: CI

on: [push, pull_request]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Java
        run: gradle build
      - name: Assemle Java Distributions
        run: gradle assembleDist
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: Distributions
          path: build/distributions/*
      
   
